const GENERATE_UUID_V1 = 'GENERATE_UUID_V1';
const GENERATE_UUID_V3 = 'GENERATE_UUID_V3';
const GENERATE_UUID_V4 = 'GENERATE_UUID_V4';
const GENERATE_UUID_V5 = 'GENERATE_UUID_V5';

const UUIDGeneratorActionTypes = {
  GENERATE_UUID_V1,
  GENERATE_UUID_V3,
  GENERATE_UUID_V4,
  GENERATE_UUID_V5
};

export default UUIDGeneratorActionTypes;